#   author: nicolas.erbetti.k@gmail.com
#   brief: This file holds the ros parameters of every node specific to the system's ros2 workspace.
#          It should be included in the ros2 full_system.launch file of the system.
#   copyright: © 2025 Nicolas Erbetti.
  
##############################################################################################################################################
 
# Setup the namespace.
/lab:
 
  ##############################################################################################################################################
  # For the apriltag segmentation node : 
  apriltag_segmentation:

    # ROS2 dedicated tag.
    ros__parameters:

      ##############################################################################################################################################
      # # # Generic parameters.

      # Update rate (in Hertz) of the main running loop of the node.
      run_rate: 15.0
      # Whether or not the node should be enabled automatically upon startup.
      auto_enable: true
      # Whether or not we publish and/or print debug messages.
      debug: true

      ##############################################################################################################################################
      # # # Image processing pipeline parameters.

      # The name of the camera used to process the pictures. Should be either camera_back or camera_front.
      camera_name: "camera_front"
      # Camera position : -1 is for the back camera, +1 is for the front camera.
      camera_position: 1
      # The lateral offset (in cm) between the camera's optical center and the robot.
      camera_offset: 0.0

      ##############################################################################################################################################
      # # # Apriltag features extraction parameters.

      # The size of the tag itself, in meters, as defined by the documentation: https://github.com/AprilRobotics/apriltag.
      tag_size: 0.111
      # The number of threads used for the april tag detection.
      nthreads: 1
      # The edge refinement factor.
      refine_edges: true
      # The covariance of the gaussian blur applied to the image.
      quad_sigma: 0.0
      # The image decimation factor.
      quad_decimate: 1.0

  ##############################################################################################################################################

  ##############################################################################################################################################
  # For the robot segmentation node :
  robot_segmentation:

    # ROS2 dedicated tag.
    ros__parameters:

      ##############################################################################################################################################
      # # # Generic parameters.

      # Update rate (in Hertz) of the main running loop of the node.
      run_rate: 20.0
      # Whether or not the node should be enabled automatically upon startup.
      auto_enable: true

      ##############################################################################################################################################
      # # # Image processing pipeline parameters.

      ##############################################################################################################################################
      # # # Yolo segmentation parameters.

      # The absolute path to the pytorch file where the weights of the YOLO model are saved.
      model_path: "/home/nicolas/personal-website/server/ros2_lab_ws/src/ai/models/best_n.pt"
      # The confidence treshold which a segmentation needs to reach to validate the detection.
      tb3_conf_threshold: 0.65

  ##############################################################################################################################################